chatbot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/urls.py
from django.urls import path
from . import views, ajax

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('result/', ajax.result, name='result'),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render
from datetime import datetime

# Create your views here.
def index(request):
    now = datetime.now()
    time = now.strftime("%H:%M")
    context = {
        'time': time,
    }
    return render(request, 'homepage/index.html', context)

homepage/templates/homepage/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <title>MathSolver</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'styles/style.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>

<body>
  <!-- partial:index.partial.html -->
  <section class="msger">
    <header class="msger-header">
      <div class="msger-header-title">
        MathBot giải bài toán lớp 3
      </div>
    </header>

    <main class="msger-chat" id="msger-chat">
      <div class="msg left-msg">
        <div class="msg-img" style="background-image: url('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRPFxBYEiVcwcYDWGFzYgM0JFWUIxzA9k5pQ&usqp=CAU');"></div>
        <div class="msg-bubble">
          <div class="msg-info">
            <div class="msg-info-name">MathBot    |    {{ time }}</div>
            <!-- <div class="msg-info-time">{{ time }}</div> -->
          </div>
          <div class="msg-text">
            Xin chào, tôi là MathBot! Hãy nhập bài toán mà bạn cần tìm lời giải vào bên dưới nhé 😄
          </div>
        </div>
      </div>

    </main>

    <form class="msger-inputarea" id="msger-inputarea">
      <input type="text" class="msger-input" id="msger-input" placeholder="Nhập tin nhắn...">
      <button type="submit" class="msger-send-btn">Gửi</button>
    </form>
  </section>
  <!-- partial -->
  <script src='https://use.fontawesome.com/releases/v5.0.13/js/all.js'></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"> </script>
  <script>

    const BOT_IMG = "{% static 'imgs/bot_icon.jpg' %}";
    const PERSON_IMG = "{% static 'imgs/user_icon.jpg' %}";
    const BOT_NAME = "MathBot";
    const PERSON_NAME = "You";

    const msgerForm = document.getElementById(".form");
    const msgerInput = document.getElementsByClassName(".msger-input");
    const msgerChat = document.getElementById(".msger-chat");

    $(".msger-send-btn").click(function(e) {
      e.preventDefault();
      $.ajax({
        url: "{% url 'homepage:result' %}",
        type: 'GET',
        data: {
          submit_text: $("#msger-input").val(),
        },
        success: function(data) {
          // console.log(data.result);
          const msgText = $("#msger-input").val();
          console.log(msgText);
          if (!msgText) return;
          appendMessage(PERSON_NAME, PERSON_IMG, "right", msgText, data.time);
  
          appendMessage(BOT_NAME, BOT_IMG, "left", data.result, data.time)
        },
      });
    });

    function appendMessage(name, img, side, text, time) {
      const msgHTML = `
                      <div class="msg ${side}-msg">
                        <div class="msg-img" style="background-image: url(${img})"></div>
                          <div class="msg-bubble">
                            <div class="msg-info">
                              <div class="msg-info-name">${name}    |    ${time}</div>
                            </div>
                            <div class="msg-text">${text}</div>
                          </div>
                        </div>
                      `;
      document.querySelector(".msger-chat").insertAdjacentHTML("beforeend",msgHTML);
      document.querySelector(".msger-chat").scrollTop += 500;
    }

  </script>


</body>

</html>